import assert from 'node:assert/strict';const base=process.env.SC_TEST_URL||'http://localhost:5173';assert(base.startsWith('http://localhost:')||base.startsWith('http://127.0.0.1:'),'Tests only run against local development');
async function login(username){const r=await fetch(base+'/api/auth',{method:'POST',headers:{'Content-Type':'application/json',Origin:base},body:JSON.stringify({username,password:'Reef!2026Cycle'})});assert.equal(r.status,200,await r.text());return r.headers.get('set-cookie').split(';')[0]}
const admin=await login('admin'),restaurant=await login('restaurant'),driver=await login('driver'),qa=await login('qa'),operator=await login('operator'),project=await login('project');
const data=async cookie=>{const r=await fetch(base+'/api/data',{headers:{Cookie:cookie}});assert.equal(r.status,200);return r.json()};
const post=async(cookie,action,body,key=crypto.randomUUID())=>{const r=await fetch(base+'/api/action',{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/json',Origin:base,'Idempotency-Key':key},body:JSON.stringify({action,data:body})});return {status:r.status,...await r.json()}};
assert.equal((await fetch(base+'/api/data')).status,401);console.log('PASS unauthenticated access rejected');
let s=await data(restaurant);assert(s.records.every(x=>x.id==='PAR-1'||x.partnerId==='PAR-1'||x.kind==='audit'&&x.actor==='USR-restaurant'));console.log('PASS restaurant row isolation');
assert.equal((await post(driver,'rule.update',{days:1,reason:'invalid'})).status,400);assert.equal((await post(qa,'batch.release',{id:'BAT-020'})).status,400);console.log('PASS role and curing checks');
const key=crypto.randomUUID(),payload={expected:111,scheduled:'2026-12-01',buckets:3,notes:'API verification'};const [a,b]=await Promise.all([post(restaurant,'pickup.create',payload,key),post(restaurant,'pickup.create',payload,key)]);assert.equal(a.status,200,JSON.stringify(a));assert.equal(b.status,200,JSON.stringify(b));assert.equal(a.result.id,b.result.id);console.log('PASS duplicate concurrent submission is idempotent');
const batch='BAT-011',snap=await data(admin);const on=snap.records.filter(x=>x.kind==='ledger'&&x.batchId===batch).reduce((a,x)=>a+x.delta,0);const q=Math.floor(on/1000*.8);const d1=await post(admin,'demand.create',{projectId:'PRO-1',weight:q,due:'2026-12-01'}),d2=await post(admin,'demand.create',{projectId:'PRO-1',weight:q,due:'2026-12-01'});const results=await Promise.all([post(admin,'reservation.create',{demandId:d1.result.id,batchId:batch,weight:q}),post(admin,'reservation.create',{demandId:d2.result.id,batchId:batch,weight:q})]);assert.equal(results.filter(x=>x.status===200).length,1,JSON.stringify(results));console.log('PASS atomic concurrent stock reservation prevents overselling');
const success=results.find(x=>x.status===200);await post(admin,'reservation.cancel',{id:success.result.id,reason:'local test completed'});await post(restaurant,'pickup.cancel',{id:a.result.id,reason:'local test completed'});console.log('PASS cancellation persisted');
for(const c of [admin,restaurant,driver,qa,operator,project])assert((await data(c)).user);console.log('PASS six role logins and persisted readback');
