import {Row} from './domain';
export function seedData(){const s:Row[]=[];const add=(kind:string,id:string,data:any)=>{const r={id,kind,created:'2026-09-01T08:00:00.000Z',...data};s.push(r);return r};
 add('rule','RULE-01',{days:365,version:1,reason:'教学场景规则，参考 Mass Oyster Project 的一年熟化实践'});
 ['蓝湾北岸熟化场','白沙南岸熟化场'].forEach((name,i)=>add('site',`SITE-${i+1}`,{name,address:i?'白沙港生态作业区 2 号':'北湾循环资源园 6 号',zones:['A1','A2','B1','B2'],capacity:100000000,active:true}));
 ['蓝湾·海风食堂','潮汐小馆','白沙牡蛎屋','港口鲜味','栈桥海鲜餐厅','听浪餐厅','渔火厨房','海角里','潮生小院','归帆海鲜','盐与海','拾贝食堂','南风渔港','望潮餐厅','蓝屿鲜生','海岸餐桌','礁石小馆','白鹭湾餐厅','帆影厨房','栖湾餐厅'].forEach((name,i)=>add('partner',`PAR-${i+1}`,{name,contact:`门店负责人 ${i+1}`,phone:`1380000${String(i+1).padStart(4,'0')}`,address:`蓝湾市${i%2?'南岸':'北岸'}滨海路 ${i*7+18} 号`,active:true}));
 for(let i=1;i<=3;i++)add('vehicle',`VEH-${i}`,{name:`蓝湾回收 ${i} 号车`,capacity:3000000,active:true});
 ['北湾牡蛎礁恢复一期','白沙滩潮间带修复','鹭湾生态示范礁','海角社区修复试验','南港栖息地重建'].forEach((name,i)=>add('project',`PRO-${i+1}`,{name,location:`蓝湾市 ${['北湾','白沙','鹭湾','海角','南港'][i]}近岸`,target:(i+1)*5000000,manager:['林海','陈青','许澜','周涛','沈岚'][i],status:'open'}));
 for(let i=1;i<=36;i++){const siteId=`SITE-${i%2+1}`,old=i<=12,daysAgo=old?410+i:50+i*2;const sealed=new Date(Date.now()-daysAgo*86400000).toISOString().slice(0,10);const due=new Date(Date.parse(sealed)+365*86400000).toISOString().slice(0,10);const b=add('batch',`BAT-${String(i).padStart(3,'0')}`,{name:`${old?'春季储备':'夏季回收'} · ${String(i).padStart(3,'0')}`,siteId,zone:['A1','A2','B1','B2'][i%4],status:'curing',quality:i===12?'quarantined':old?'released':'unreleased',sealedAt:sealed,due,days:365,ruleVersion:1});
  for(let j=0;j<6;j++){const n=(i-1)*6+j+1,q=(90+(n*17)%160)*1000,partnerId=`PAR-${n%20+1}`,pid=`PICK-${String(n).padStart(4,'0')}`,rid=`REC-${String(n).padStart(4,'0')}`;add('pickup',pid,{partnerId,expected:q,scheduled:sealed,collectedAt:sealed,status:'received',collectedWeight:q+3000,buckets:5,tripId:`HIST-${i}`,created:sealed+'T08:00:00Z'});add('receipt',rid,{pickupId:pid,partnerId,siteId,gross:q+13000,tare:10000,reject:3000,accepted:q,reason:'分拣杂物 3 kg',status:'received',created:sealed+'T10:00:00Z'});add('input',`IN-${n}`,{batchId:b.id,receiptId:rid,qty:q});add('ledger',`LED-IN-${n}`,{batchId:b.id,delta:q,reason:'入库投料',ref:`IN-${n}`,actor:'USR-operator'});}
  if(old)add('inspection',`INS-${i}`,{batchId:b.id,result:i===12?'fail':'pass',notes:i===12?'发现塑料杂物，隔离复检':'干燥、洁净，无异味，抽样合格',actor:'USR-qa'});
 }
 for(let i=217;i<=300;i++){const status=i<=225?'collected':i<=237?'assigned':i<=290?'requested':'cancelled';add('pickup',`PICK-${String(i).padStart(4,'0')}`,{partnerId:`PAR-${i%20+1}`,expected:(80+i%120)*1000,scheduled:new Date(Date.now()+(i%5-2)*86400000).toISOString().slice(0,10),status,buckets:4,tripId:i<=237?'TRIP-DEMO':undefined,collectedWeight:status==='collected'?150000:undefined,notes:i%5===0?'请从后门装货':''})}
 for(let i=1;i<=36;i++){const pickups=s.filter(x=>x.kind==='pickup'&&x.tripId===`HIST-${i}`);add('trip',`HIST-${i}`,{name:`历史回收线 ${i}`,driverId:'USR-driver',vehicleId:`VEH-${i%3+1}`,scheduled:pickups[0].scheduled,status:'completed',pickupIds:pickups.map(x=>x.id),created:pickups[0].created})}
 for(const p of s.filter(x=>x.kind==='pickup'&&x.status==='collected'))p.scheduled=new Date(Date.now()-86400000).toISOString().slice(0,10);
 add('trip','TRIP-DEMO',{name:'北岸沿海线',driverId:'USR-driver',vehicleId:'VEH-1',scheduled:new Date().toISOString().slice(0,10),status:'assigned',pickupIds:s.filter(x=>x.kind==='pickup'&&x.tripId==='TRIP-DEMO').map(x=>x.id)});
 for(let i=1;i<=20;i++){const projectId=`PRO-${i%5+1}`,d=add('demand',`DEM-${i}`,{projectId,qty:400000,due:'2026-12-01',notes:'生态修复用洁净牡蛎壳',status:'open'});if(i<=10){const batchId=`BAT-${String(i).padStart(3,'0')}`;const rs=add('reservation',`RES-${i}`,{demandId:d.id,projectId,batchId,qty:400000,shipped:i<=6?300000:0,status:'active'});if(i<=6){add('dispatch',`DSP-${i}`,{reservationId:rs.id,demandId:d.id,projectId,batchId,siteId:`SITE-${i%2+1}`,qty:300000,vehicle:'蓝湾生态运输车',status:i<=4?'received':'shipped',received:i<=4?295000:undefined,reason:i<=4?'运输散落 5 kg':''});add('ledger',`LED-OUT-${i}`,{batchId,delta:-300000,reason:'项目发运',ref:`DSP-${i}`,actor:'USR-dispatcher'});if(i<=4)add('deployment',`DEP-${i}`,{dispatchId:`DSP-${i}`,projectId,batchId,qty:200000,date:'2026-09-01',location:'近岸恢复区 A 点',notes:'按修复方案铺设'})}}}
 add('audit','AUD-SEED',{action:'demo.initialize',target:'蓝湾演示组织',actor:'system',actorName:'系统',details:'初始化关联一致的模拟教学数据；非真实公司经营数据'});
 return s;
}
