import {env} from 'cloudflare:workers';
import {seedData} from './seed';
import {Row,User,roles,apply,visible,assert,str} from './domain';
export function db(){if(!env.DB)throw new Error('数据库暂不可用');return env.DB}
export const hex=(a:ArrayBuffer)=>Array.from(new Uint8Array(a)).map(v=>v.toString(16).padStart(2,'0')).join('');
export async function digest(s:string){return hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))}
export async function password(p:string,salt:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},key,256))}
export async function bootstrap(){const d=db();if(await d.prepare('SELECT id FROM business_revision WHERE id=1').first())return;const st=[d.prepare('INSERT INTO business_revision(id,version) VALUES(1,0)')];const seed=seedData();for(let i=0;i<seed.length;i+=20){const group=seed.slice(i,i+20);st.push(d.prepare(`INSERT INTO business_records(id,kind,data) VALUES ${group.map(()=>'(?,?,?)').join(',')}`).bind(...group.flatMap(r=>[r.id,r.kind,JSON.stringify(r)])))}for(const [role,name]of Object.entries(roles))st.push(d.prepare('INSERT INTO users(id,username,name,role,scope,hash,salt,active) VALUES(?,?,?,?,?,?,?,1)').bind('USR-'+role,role,name,role,role==='restaurant'?'PAR-1':role==='operator'?'SITE-1':role==='project'?'PRO-1':'all','d86900b95e513b5b017509e963e43220c26564591d2eb89dc70e59bdc7a6cc94','1983e1fa26801d8290b28644bd5677e4'));try{await d.batch(st)}catch(e){if(!await d.prepare('SELECT id FROM business_revision WHERE id=1').first())throw e}}
export async function snapshot(){const result=await db().prepare("SELECT id,kind,data FROM business_records UNION ALL SELECT '__revision','__revision',CAST(version AS TEXT) FROM business_revision WHERE id=1").all<any>();const v=result.results.find(x=>x.kind==='__revision');return {version:Number(v?.data||0),state:result.results.filter(x=>x.kind!=='__revision').map(x=>JSON.parse(x.data)) as Row[]}}
export async function user(req:Request):Promise<User>{const token=(req.headers.get('cookie')||'').match(/(?:^|;\s*)sc_session=([^;]+)/)?.[1];assert(token,'请先登录');const u=await db().prepare('SELECT u.id,u.username,u.name,u.role,u.scope,u.active FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires>? AND u.active=1').bind(await digest(token),Date.now()).first<User>();assert(u,'登录已过期，请重新登录');return u}
export async function stateFor(u:User){const {state}=await snapshot();const us=await db().prepare('SELECT id,username,name,role,scope,active FROM users').all<User>();return {user:u,records:visible(state,u),users:u.role==='admin'?us.results:us.results.filter(x=>['driver','operator','qa','project'].includes(x.role)).map(x=>({id:x.id,name:x.name,role:x.role,scope:x.scope,active:x.active}))}}
export async function mutate(u:User,action:string,b:any,key:string){assert(/^[\w-]{10,100}$/.test(key),'缺少有效操作标识');const d=db();const previous=await d.prepare('SELECT result,user_id FROM commands WHERE id=?').bind(key).first<any>();if(previous){assert(previous.user_id===u.id,'操作标识冲突');return JSON.parse(previous.result)}
 const snap=await snapshot(),before=new Map(snap.state.map(x=>[x.id,JSON.stringify(x)]));
 if(action==='trip.create'){const dr=await d.prepare("SELECT id FROM users WHERE id=? AND role='driver' AND active=1").bind(b.driverId).first();assert(dr,'请选择有效司机')}
 const {result,state}=apply(snap.state,u,action,b);const statements=[d.prepare('INSERT INTO transaction_guard(id,valid) VALUES(?,CASE WHEN (SELECT version FROM business_revision WHERE id=1)=? THEN 1 ELSE NULL END)').bind(key,snap.version),d.prepare('UPDATE business_revision SET version=version+1 WHERE id=1')];
 for(const r of state){const data=JSON.stringify(r);if(before.get(r.id)!==data)statements.push(d.prepare('INSERT INTO business_records(id,kind,data) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').bind(r.id,r.kind,data))}
 statements.push(d.prepare('INSERT INTO commands(id,user_id,result,created) VALUES(?,?,?,?)').bind(key,u.id,JSON.stringify(result),new Date().toISOString()),d.prepare('DELETE FROM transaction_guard WHERE id=?').bind(key));
 try{await d.batch(statements)}catch(e){const prior=await d.prepare('SELECT result FROM commands WHERE id=? AND user_id=?').bind(key,u.id).first<any>();if(prior)return JSON.parse(prior.result);if(String(e).includes('transaction_guard'))throw new Error('其他用户刚更新了数据，请刷新后重试');throw e}return result;
}
export function secure(req:Request){const origin=req.headers.get('origin');if(origin)assert(origin===new URL(req.url).origin,'不允许跨站提交');assert((req.headers.get('content-type')||'').includes('application/json'),'请求格式必须为 JSON')}
export function response(data:any,status=200,headers:Record<string,string>={}){return Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}})}
export function fail(e:any){const m=String(e?.message||e);const expected=!/D1_|SQLITE_|binding|TypeError|undefined/i.test(m);if(!expected)console.error('ShellCycle request failed',m);return response({error:expected?m:'业务服务暂不可用，请稍后重试；输入尚未保存'},m.includes('登录')?401:expected?400:503)}
